name: Zhao Lü
url: http://zlu.me/
description: zlu
author: zlu
rss_path: feeds
markdown: kramdown
redcarpet:
  extensions: ["strikethrough"]
pygments: true
port: 4000
exclude: ["vendor"]
collections:
  archives:
    output: true
    permalink: /archive/:title/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap