name: blog@zlu
url: http://www.zlu.me
description: Personal blog of Zhao Lu
author: Zhao Lu
rss_path: feeds
markdown: kramdown
redcarpet:
  extensions: ["strikethrough"]
pygments: true
port: 6000
exclude: ["vendor"]