backend:
  name: github
  repo: zlu/zlu.github.io
  branch: main
  site_domain: zlu.me
  app_id: Ov23lige46jUA9fP3amk

media_folder: "assets/images/uploads"

collections:
  - name: "travels"
    label: "Travels"
    folder: "travels/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "drafts"
    label: "Drafts"
    folder: "_drafts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    extension: ".md"
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "courses"
    label: "Tutored Courses"
    folder: "_data/courses/"
    create: true
    slug: "{{university | slugify}}"
    format: "yaml-frontmatter"
    extension: ".yml"
    fields:
      - { label: "University Name", name: "university", widget: "string" }
      - label: "Courses"
        name: "courses"
        widget: "list"
        fields:
          - {
              label: "Course Code",
              name: "code",
              widget: "string",
              required: false,
            }
          - { label: "Course Title", name: "title", widget: "string" }
          - {
              label: "Department/Notes",
              name: "department",
              widget: "string",
              required: false,
            }
  - name: "ai-glossary"
    label: "AI Glossary"
    folder: "_ai-glossary/"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Term", name: "title", widget: "string" }
      - { label: "Synonyms", name: "synonyms", widget: "list", required: false }
      - {
          label: "Related Terms",
          name: "related",
          widget: "list",
          required: false,
        }
      - { label: "Definition", name: "body", widget: "markdown" }
  - name: "med-glossary"
    label: "Medicine Glossary"
    folder: "_med-glossary/"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Term", name: "title", widget: "string" }
      - { label: "Term English", name: "term-en", widget: "list", required: false }
      - {
          label: "Related Terms",
          name: "related",
          widget: "list",
          required: false,
        }
      - { label: "Definition", name: "body", widget: "markdown" }
