backend:
  name: github
  repo: zlu/zlu.github.io
  branch: main
  auth_type: implicit
  auth_url: https://github.com/login/oauth/authorize
  api_url: https://api.github.com
  site_url: https://www.zlu.me
  base_url: /admin

media_folder: "assets/images/uploads"

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'drafts'
    label: 'Drafts'
    folder: '_drafts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    format: "frontmatter"
    extension: ".md"
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "courses"
    label: "Tutored Courses"
    folder: "_data/courses/"
    create: true
    slug: "{{university | slugify}}"
    format: "yaml-frontmatter"
    extension: ".yml"
    fields:
      - { label: "University Name", name: "university", widget: "string" }
      - label: "Courses"
        name: "courses"
        widget: "list"
        fields:
          - { label: "Course Code", name: "code", widget: "string", required: false }
          - { label: "Course Title", name: "title", widget: "string" }
          - { label: "Department/Notes", name: "department", widget: "string", required: false }